# Generated by Django 5.2.11 on 2026-04-25 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funcionarios', '0003_alter_funcionario_cidade_alter_funcionario_cpf_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='funcionario',
            name='endereco',
        ),
        migrations.AddField(
            model_name='funcionario',
            name='bairro',
            field=models.CharField(blank=True, max_length=100, verbose_name='Bairro'),
        ),
        migrations.AddField(
            model_name='funcionario',
            name='cep',
            field=models.CharField(default=0, max_length=9, verbose_name='CEP'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='funcionario',
            name='estado',
            field=models.CharField(blank=True, max_length=2, verbose_name='Estado'),
        ),
        migrations.AddField(
            model_name='funcionario',
            name='rua',
            field=models.CharField(blank=True, max_length=255, verbose_name='Rua'),
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='cidade',
            field=models.CharField(blank=True, max_length=100, verbose_name='Cidade'),
        ),
    ]
