# Generated by Django 5.2.11 on 2026-04-25 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funcionarios', '0004_remove_funcionario_endereco_funcionario_bairro_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='funcionario',
            name='cep',
            field=models.CharField(blank=True, max_length=9, null=True, verbose_name='CEP'),
        ),
    ]
