# Generated by Django 5.2.11 on 2026-04-25 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funcionarios', '0005_alter_funcionario_cep'),
    ]

    operations = [
        migrations.AddField(
            model_name='funcionario',
            name='categoria_estadual',
            field=models.CharField(blank=True, choices=[('prof_efetivo', 'Professor/Docente Efetivo/Estável'), ('prof_contratado', 'Professor/Docente Contratado'), ('agente_efetivo', 'Agente Organização Escolar Efetivo/Estável'), ('agente_contratado', 'Agente Organização Escolar Contratado')], max_length=50, null=True, verbose_name='Categoria Estadual'),
        ),
        migrations.AddField(
            model_name='funcionario',
            name='tipo_funcionario',
            field=models.CharField(choices=[('estadual', 'Estadual'), ('municipal', 'Municipal'), ('terceirizado', 'Terceirizado')], default='municipal', max_length=20, verbose_name='Tipo de Funcionário'),
        ),
    ]
