# Generated by Django 5.2.11 on 2026-04-25 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funcionarios', '0006_funcionario_categoria_estadual_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='funcionario',
            name='categoria_estadual',
        ),
        migrations.AddField(
            model_name='funcionario',
            name='cargo_estadual',
            field=models.CharField(blank=True, choices=[('professor', 'Professor/Docente'), ('agente', 'Agente de Organização Escolar')], max_length=20, null=True, verbose_name='Cargo Estadual'),
        ),
        migrations.AddField(
            model_name='funcionario',
            name='vinculo',
            field=models.CharField(blank=True, choices=[('efetivo', 'Efetivo'), ('estavel', 'Estável'), ('contratado', 'Contratado')], max_length=20, null=True, verbose_name='Vínculo'),
        ),
    ]
